version: 2.1

aliases:
  - &restore-cache
    restore_cache:
      key: npm-{{ checksum "package.json" }}

  - &npm-install
    run:
      name: Install test dependencies
      command: npm install

  - &save-cache
    save_cache:
      key: npm-{{ checksum "package.json" }}
      paths:
        - ~/repo/node_modules

  - &filter-main
    branches:
      only:
        - main

orbs:
  node: circleci/node@2.0.3
  heroku: circleci/heroku@1.2.6

jobs:
  lint:
    docker:
      - image: cimg/node:14.17.4
    working_directory: ~/repo
    steps:
      - checkout
      - *restore-cache
      - *npm-install
      - *save-cache
      - run: npm run lint
  test:
    docker:
      - image: cimg/node:14.17.4
    working_directory: ~/repo
    steps:
      - checkout
      - *restore-cache
      - *npm-install
      - *save-cache
      - run: npm run test
  build:
    docker:
      - image: cimg/node:14.17.4
    working_directory: ~/repo
    steps:
      - checkout
      - *restore-cache
      - *npm-install
      - *save-cache
      - run: npm run build
  # deploy:
  #   working_directory: ~/repo
  #   environment:
  #     HEROKU_APP: 'guarded-escarpment-80478'
  #   steps:
  #     - checkout
  #     - run:
  #         name: Setup Heroku
  #         command: bash .circleci/setup-heroku.sh

  #     - run:
  #         command: |
  #           git push heroku sequential-branch-filter:master
  #           sleep 5
  #           heroku restart

workflows:
  lint-test:
    jobs:
      - lint
      - test
  build-deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only:
                - main
