version: 2.1

orbs:
  node: circleci/node@2.0.3
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Run build
          command: npm run build

workflows:
  run-ci:
    jobs:
      - build_and_test
      - heroku/deploy-via-git:
          requires:
            - build_and_test
